In [1]:
#Question 1
word = input("Please enter a string of alphabets:")

length = len(word)
word = word.replace("a","i")
print(word)

Please enter a string of alphabets:aaaaiuou
iiiiiuou


In [3]:
#Question 2
n = int(input("Please enter any number:"))
for i in range(n):
    for j in range(n):
        print(i+1,'*',j+1, '=',(i+1)*(j+1))


Please enter any number:5
1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25


In [4]:
#Question 3
sentence = input("Please enter a sentence:")
list1 = sentence.split()
list1 = sorted(list1, key=len)
list2 =[]
for i in range(len(list1)):
    list2.append(len(list1[i]))

list_final = []
for i in range(len(list1)):
    list_final.append((list2[i],list1[i]))
    
print(list_final)

Please enter a sentence:this is a long sentence
[(1, 'a'), (2, 'is'), (4, 'this'), (4, 'long'), (8, 'sentence')]


In [16]:
def sort_dic(urll):
    if len(urll) == 1:
        return urll
    else:
        sort_dict1 = sorted(urll, key=urll.get, reverse=True)
        sort_dict2 = {}
        for i in sort_dict1:
            sort_dict2[i] = urll[i]
        return sort_dict2

In [17]:
#Question 4

fh = open("question.txt")
text =fh.read()
text1 = text.lower()
wordlist = text1.split()

#print(wordlist)
freq=dict()
for i in wordlist:
    if i in freq:
        freq[i]+=1;
    else:
        freq[i]=1;
        

comp = sort_dic(freq)
print(comp)

#print(sort_dict)



#freq_final = freq_sorted[0:5]
#for w in freq_final:
    #if w in freq:
       # print(freq[w]," ", w)


{'business': 6, 'the': 5, 'of': 5, 'is': 4, 'in': 4, 'columbia': 3, 'school': 3, 'schools': 3, 'city': 2, 'new': 2, 'york': 2, 'one': 2, 'university': 1, 'manhattan': 1, 'established': 1, '1916': 1, 'oldest': 1, 'world': 1, 'it': 1, 'six': 1, 'ivy': 1, 'league': 1, 'and': 1, 'among': 1, 'most': 1, 'selective': 1, 'top': 1}


In [ ]:
#Question 5
#\d{4}-\d{2}-\d{2}$
#\b\d{5}-\d{4}\b|\b\d{5}\b
#\w.+@\w.+.com

In [5]:
#Question 6
import numpy as np

a = np.array([1,2,2,3,4,4,4])
b = np.array([2,2,4,7])

intersect = []
for i in range(len(a)):
    for j in range(len(b)):
        if (a[i] == b[j]) & (i not in intersect):
            intersect.append(i)
      
                    
len(a)               

                        


7

In [6]:
print(intersect)

[1, 2, 4, 5, 6]


In [5]:
import numpy as np
a = np.array([[1,2,3],[2,3,4]])

In [6]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [11]:
b = np.array([[1,1,1],[2,2,2]])
b

array([[1, 1, 1],
       [2, 2, 2]])

In [8]:
a+b

array([[2, 3, 4],
       [4, 5, 6]])

In [9]:
a*b

array([[1, 2, 3],
       [4, 6, 8]])

In [12]:
a>b


array([[False,  True,  True],
       [False,  True,  True]], dtype=bool)

In [13]:
np.arrange(a)

AttributeError: module 'numpy' has no attribute 'arrange'

In [14]:
np.sort(a,axis = 0)

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
a = np.array([[4,2,3],[3,3,4]])

In [19]:
np.sort(a,axis = 0)

array([[3, 2, 3],
       [4, 3, 4]])

In [20]:
c = [1,2,3,4,5]

In [21]:
for i in c:
    print(i)

1
2
3
4
5


In [25]:
L = [i for i in range(10)]

In [26]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
L = [c*2 for c in '10']

In [28]:
L

['11', '00']

In [29]:
L.remove('11')

In [30]:
L

['00']

In [2]:
L = [1,2,3,4,5,6]

In [32]:
L[0:-1:2]

[1, 3, 5]

In [5]:
L[-1:]

[6]

In [11]:
l = [2,5,1,4,5]

In [12]:
a =l.sort()
print(a)

None


In [13]:
a

In [14]:
print(a)

None


In [15]:
15%5

0

In [16]:
16%5

1

In [17]:

a = ['a', 1, 'b',2]
print(len(a))

4


In [18]:
a = ['Columbia', 'business', 'school']

In [19]:
a[-2:]

['business', 'school']

In [20]:
a.sort()

In [23]:
a.sort(key=str.lower)

In [24]:
a

['business', 'Columbia', 'school']

In [25]:
matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    
]

In [26]:
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [33]:
dicc =dict.fromkeys(['a','b'],0)

In [31]:
dict

dict

In [34]:
print(dicc)

{'a': 0, 'b': 0}


In [2]:
import numpy as np
a = np.ndarray[1,1,2]

TypeError: 'type' object is not subscriptable

In [3]:
big_array = np.zeros(shape = (6,2))
for it in range(6):
    big_array[it] = (it,it)
big_array[0]

array([ 0.,  0.])

In [4]:
a = [1,2,3]
a[0]

1

In [2]:
import numpy as np
a = np.arange(6)

In [3]:
print(a)

[0 1 2 3 4 5]
